#!/usr/bin/env python3
"""Convert a raw byte file to COR24 load-and-go L records."""
import argparse
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("input")
parser.add_argument("address", type=lambda value: int(value, 0))
parser.add_argument("output")
parser.add_argument(
    "--skip-zero",
    action="store_true",
    help="omit records whose complete payload is zero",
)
parser.add_argument(
    "--ranges-asm",
    help="write omitted half-open address ranges as COR24 assembly words",
)
args = parser.parse_args()

data = Path(args.input).read_bytes()
omitted = []
with Path(args.output).open("w", encoding="ascii", newline="\n") as out:
    for offset in range(0, len(data), 36):
        chunk = data[offset:offset + 36]
        if args.skip_zero and chunk and not any(chunk):
            start = args.address + offset
            end = start + len(chunk)
            if omitted and omitted[-1][1] == start:
                omitted[-1] = (omitted[-1][0], end)
            else:
                omitted.append((start, end))
            continue
        out.write(f"L{args.address + offset:06X}{chunk.hex().upper()}\n")

if args.ranges_asm:
    with Path(args.ranges_asm).open("w", encoding="ascii", newline="\n") as out:
        out.write("; Generated by bin_to_lgo.py; end addresses are exclusive.\n")
        out.write("snobol_zero_ranges:\n")
        for start, end in omitted:
            out.write(f"        .word 0x{start:06X},0x{end:06X}\n")
        out.write("        .word 0xFFFFFF,0xFFFFFF\n")
